name: hola mundo

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *" # ejecuta cada minuto

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Muestra mensaje hola mundo
        run: echo "hola mundo, Felipe"
