name: hola mundo

on:
   push:
     branches:
      - main
   pull_request:
      branches:
      - main
  # schedule:
  #   - cron: "*/5 * * * *" # ejecuta cada minuto
   workflow_dispatch: # manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Muestra mensaje hola mundo
        run: | 
           echo "hola mundo, Felipe"
           echo "segunda línea"
           
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Lista los archivos del repositorio
        run: |
          echo "El repositorio ${{ github.repository }} contiene los siguientes archivos:"
          tree
