name: variables

on:
  workflow_dispatch:

# variables a nivel del workflow completo
env:
  variable_global_1: Valor de la variable

jobs:
  job-1:
    runs-on: ubuntu-latest
    # variable a nivel del job
    env: 
      variable_job: variable a nivel de este job
    steps:
      - name: step 1 del job-1
        run: |
          echo el valor de la variable es $variable_global_1
          echo 'otra forma de escribir la variable ${{ env.variable_global_1 }}'
          echo 'también podemos definir variables a nivel de un único job ${{env.variable_job}}'
          echo 'o variables a nivel de step como esta ${{ env.variable-step }}'
        # variable a nivel del step
        env:
          variable-step: variable a nivel de un step

      - name: step 2 del job-1
        run: |
          echo seguimos con acceso a la variable de WF $variable_global_1
          echo seguimos con acceso a la variable de job $variable_job
          echo no tenemos acceso a la variable step ${{env.variable-step}}

  job-2:
    runs-on: ubuntu-latest
    steps:
      - name: step 1 del job-2
        run: |
          echo seguimos con acceso a la variable de WF $variable_global_1
          echo no tenemos acceso a la variable de job 1 $variable_job
          echo no tenemos acceso a la variable step ${{env.variable-step}}
